version: '3'

services:
  web:
    container_name: yandex_poster
    image: abramovio/devman_1week_yandex_poster:latest
    restart: always
    command: gunicorn django_yandex_poster.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ALLOWED_HOSTS={your_server_ip_address}, {another ip address}
      - SECRET_KEY={your_secret_key}
    volumes:
      - ./media:/yandex_poster/media
    ports:
      - '8000:8000'