version: '3'

services:
  web:
    container_name: yandex_poster
    image: abramovio/devman_1week_yandex_poster:latest
    restart: always
    command: gunicorn test_traffic_light.wsgi:application --bind 0.0.0.0:8000
    environment:
      - STAGE=176.119.159.88
    volumes:
      - ./media:/yandex_poster/media
    ports:
      - 8000:8000
