# Generated by Django 3.2.9 on 2021-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер при отображении'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(db_index=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(db_index=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
